### PR TITLE
Player favourites

### PR DESCRIPTION
**Pull request by MartijnKooij**
A suggested implementation for marking players as favourite.

Questions:
- We don't really have a player management place. Since the match player selection window is currently the only place where favourites are useful I have implemented it there.
- I would rather have an empty / yellow star toggle to indicate favourite players, but I could not yet find the "right" way to do that in ionic. Before I dug deeper I wanted to check if that would indeed be a better UI.
- I think nick name assigning should probably also be moved to the new `PlayerService` but I did not want to move too much in 1 PR.
- I never did any Firebase stuff before, is this indeed the right way to update an array property?

I have also updated player sorting based on organizer + selected + favourite + nickname.

### CODE REVIEW

**Comment by PsiOps** [comment]
Looks pretty damn sweet @MartijnKooij ! I will have a bit more detailed look tonight and probably merge deploy then.

**Comment by MartijnKooij** [comment]
Thanks, but let me at least replace the ugly default toggle with a star toggle or something. Right now it's hard to guess what the toggle would do.

**Comment by PsiOps** [comment]
Yeah sure! Indeed a star toggle was what I had in mind. So I will wait with the merge then.

**Comment by MartijnKooij** [comment]
Took me quite long to realize that if you no longer use a ion-toggle component, you have to toggle the boolean yourself... Duh...
I pushed the changes with the star toggle, what colour do you want? I picked orange for now, feels a bit random, looks ok.

**Comment by PsiOps** [comment]
Sorry missed your update, will deploy tonight!

**Comment by PsiOps** [comment]
To answer your "Questions":

- We don't really have a player management place. Since the match player selection window is currently the only place where favourites are useful I have implemented it there.
_Exactly how I feel about it_
- I would rather have an empty / yellow star toggle to indicate favourite players, but I could not yet find the "right" way to do that in ionic. Before I dug deeper I wanted to check if that would indeed be a better UI.
_I think this is what you found in the end right?_
- I think nick name assigning should probably also be moved to the new PlayerService but I did not want to move too much in 1 PR.
_Sounds like it belongs there indeed, I'll create a Trello Card for that_
- I never did any Firebase stuff before, is this indeed the right way to update an array property?
_That's exactly how it's done, said the Firebase expert_

**Comment by MartijnKooij** [comment]
Thanks for merging. I see that the updated sort order does not appear to work? Shall we create a new issue for that, as the list becomes longer it becomes more annoying that the list is unordered...

**Pull request merged**
